############
# Parameters
############

######
# Data
######
# str: blobs, mnist, fashion_mnist, cifar10, cifar100
dataset: "fashion_mnist"
input_shape: [1, 28, 28]
n_classes: 10
#
# dataset: "cifar10"
# input_shape: [3, 32, 32]
# n_classes: 10
#
# dataset: "blobs"
# input_shape: [2, 1, 1]
# n_classes: 64
# float: Use subset of dataset: float (0, 1]
subset_ratio: 0.05

###########
# Evolution
###########
# Network topology search with genetic optimization.
n_generations: 9999999999
n_agents: 4
global_mutation_rate: 0.5
local_mutation_rate: 0.1
increase_epochs_every_n_epochs: -1

##########
# Training
##########
# Parameter optimization with gradient descent.
n_epochs: 1
batch_size_test: 500

###############
# Miscellaneous
###############
use_gpu: true
random_seed: 69
n_workers: 1
stats_every_n_epochs: 1

#############
# Tensorboard
#############
add_hyperparameters: false
