#################
# Hyperparameters
#################

hparam:

  # Mutable hyperparameters for network optimization with gradient descent.

  learning_rate:
    mutate: true
    dtype: "float"
    ptype: "scalar"
    val: 1.0e-3
    val_min: 1.0e-6
    val_max: 1.0e-2

  batch_size:
    mutate: true
    dtype: "int"
    ptype: "scalar"
    val: 128
    val_min: 1
    val_max: 128

  dropout_rate:
    mutate: true
    dtype: "float"
    ptype: "scalar"
    val: 0.1
    val_min: 0.0
    val_max: 0.5

  weight_decay:
    mutate: true
    dtype: "float"
    ptype: "scalar"
    val: 1.0e-5
    val_min: 1.0e-8
    val_max: 1.0e-2

  # Mutable hyperparameters for network topology optimization.

  n_dims_hidden:
    mutate: true
    dtype: "int"
    ptype: "vector"  # list, array?
    val: 32
    val_min: 4
    val_max: 128

  n_layers_hidden:
    mutate: false
    dtype: "int"
    ptype: "scalar"
    val: 8
    val_min: 1
    val_max: 8
