#################
# Hyperparameters
#################

hparam:

  # Mutable hyperparameters for network optimization with gradient descent.

  learning_rate:
    mutate: true
    dtype: "float"
    ptype: "scalar"
    val: 1.0e-3
    val_min: 1.0e-6
    val_max: 1.0e-2
    step_size: 1.0e-5

  batch_size:
    mutate: true
    dtype: "int"
    ptype: "scalar"
    val: 32
    val_min: 1
    val_max: 128
    step_size: 1

  dropout_rate:
    mutate: true
    dtype: "float"
    ptype: "scalar"
    val: 0.5
    val_min: 0.0
    val_max: 0.5
    step_size: 0.001

  weight_decay:
    mutate: true
    dtype: "float"
    ptype: "scalar"
    val: 1.0e-5
    val_min: 1.0e-8
    val_max: 1.0e-2
    step_size: 1.0e-6

  # Mutable hyperparameters for network topology optimization.

  n_dims_hidden:
    mutate: true
    dtype: "int"
    ptype: "vector"  # list, array?
    val: 32
    val_min: 4
    val_max: 256
    step_size: 1

  n_layers_hidden:
    mutate: false
    dtype: "int"
    ptype: "scalar"
    val: 4
    val_min: 1
    val_max: 8
    step_size: 1
